Update babel.md
gatsbyjs/gatsby-mr pull request #13
Opened 2020-05-12 03:14 UTC by abhaypawar

Translated doc/babel.md successfully. I request everyone to kindly check this.
Thanks.
@spielers

2020-05-12 04:05 UTC, spielers requested changes

2020-05-12 04:05 UTC, spielers commented on docs/docs/babel.md
> +## कोणत्या ब्राउझरचे समर्थन करावे हे निर्दिष्ट कसे करावे
change karavo with karal !

2020-05-12 04:05 UTC, spielers commented on docs/docs/babel.md
> +आपण केवळ नवीन ब्राउझरला लक्ष्य केले असल्यास, आपण कोणत्या ब्राउझरवर समर्थित आहात यावर गॅटस्बीला कसे शिकवायचे यासाठी [ब्राउझर समर्थन] (/ दस्तऐवज / ब्राउझर-समर्थन /) दस्तऐवज पृष्ठ पहा आणि नंतर बाबेल केव
dont try to translate the english words from links, links needs to be lin English for perfect work

2020-05-12 06:02 UTC, abhaypawar reviewed
Eliminated the flaws. Please check now.

2020-05-12 06:23 UTC, visshaljagtap requested changes

2020-05-12 06:23 UTC, visshaljagtap commented on docs/docs/babel.md
> +अधिक प्रगत कॉन्फिगरेशनसाठी, आपण डीफॉल्टची कॉपी देखील येथे करु शकता  [`babel-preset-gatsby`](https://github.com/gatsbyjs/gatsby/tree/master/packages/babel-preset-gatsby)आणि आपल्या गरजा भागविण्यासाठी त
better to use कस्टमाईज rather than सानुकूलित

2020-05-12 06:23 UTC, visshaljagtap commented on docs/docs/babel.md
> +डीफॉल्ट .babelrc सेटअपसह गॅटस्बी शिप्स बहुतेक साइट्ससाठी कार्य करतात. आपण सानुकूल बाबेल प्रीसेट किंवा प्लगइन जोडू इच्छित असल्यास, आपण आपल्या साइटच्या रूट्स आपले स्वतःचे `.babrcrc` तयार करू शकता.आयात
use कस्टम instead of सानुकूल

2020-05-12 06:23 UTC, visshaljagtap commented on docs/docs/babel.md
> +## सानुकूल .babelrc फाईल कशी वापरावी
use कस्टम instead of सानुकूल

2020-05-12 06:30 UTC, abhaypawar reviewed
Edited now. I request you to check, please.

2020-08-03 05:02 UTC, visshaljagtap approved these changes

2020-08-15 01:31 UTC, shivaylamba approved these changes

2020-10-01 19:04 UTC, spielers requested changes

2020-10-01 19:04 UTC, spielers commented on docs/docs/babel.md
> +जुन्या ब्राऊजरला समर्थन देत असताना- गॅटस्बी (babel](https://babeljs.io/) आधुनिक जावास्क्रिप्ट लिहिण्यास समर्थन देण्यासाठी वापरतो
Check the square bracket

2020-10-01 19:04 UTC, spielers commented on docs/docs/babel.md
> +याचा अर्थ असा आहे की आपली जावास्क्रिप्ट जुन्या ब्राउझरवर कार्य करते हे सुनिश्चित करण्यासाठी स्वयंचलितपणे संकलित केली आहे. पॉलीफिल देखील स्वयंचलितपणे जोडली जातात - जुन्या ब्राउझरवर रहस्यमयपणे खंडित कर
javascript should be written in the English language only.

2020-10-01 19:04 UTC, spielers commented on docs/docs/babel.md
> +आपण केवळ नवीन ब्राउझरला लक्ष्य केले असल्यास, आपण कोणत्या ब्राउझरवर समर्थित आहात यावर गॅटस्बीला कसे शिकवायचे यासाठी [Browser Support](/docs/browser-support/) दस्तऐवज पृष्ठ पहा आणि नंतर बाबेल केवळ या ब
ब्राउझरला ==>ब्राउझरवर  add लक्ष केंद्रित केले असल्यास . every पृष्ठ  should be replaced with पेज

2020-10-01 19:04 UTC, spielers commented on docs/docs/babel.md
> +डीफॉल्ट .babelrc सेटअपसह गॅटस्बी शिप्स बहुतेक साइट्ससाठी कार्य करतात. आपण कस्टम बाबेल प्रीसेट किंवा प्लगइन जोडू इच्छित असल्यास, आपण आपल्या साइटच्या रूट्स आपले स्वतःचे `.babrcrc` तयार करू शकता.आयात कर
डिफॉल्ट .babelrc सेटअप फाईल बरोबर येते  anni te + add this in front then add बहुतेक साइट्ससाठी कार्य करतात

साइटच्या रूटमध्ये

2020-10-01 19:04 UTC, spielers commented on docs/docs/babel.md
> +डीफॉल्ट .babelrc सेटअपसह गॅटस्बी शिप्स बहुतेक साइट्ससाठी कार्य करतात. आपण कस्टम बाबेल प्रीसेट किंवा प्लगइन जोडू इच्छित असल्यास, आपण आपल्या साइटच्या रूट्स आपले स्वतःचे `.babrcrc` तयार करू शकता.आयात कर
आयात करा should be replaced with import kara

2020-10-01 19:04 UTC, spielers commented on docs/docs/babel.md
> +अधिक प्रगत कॉन्फिगरेशनसाठी, आपण डीफॉल्टची कॉपी देखील येथे करु शकता  [`babel-preset-gatsby`](https://github.com/gatsbyjs/gatsby/tree/master/packages/babel-preset-gatsby)आणि आपल्या गरजा भागविण्यासाठी त
add tayaar after yethe 


ane aplya garjha bhagavnyasthi tyana customize karu shakta.
 add this

2020-10-02 03:29 UTC, visshaljagtap reviewed
make necessary changes suggested @abhaypawar

2020-10-03 16:40 UTC, closed without merging