Update adding-forms.md
gatsbyjs/gatsby-mr pull request #26
Opened 2020-10-03 17:12 UTC by abhaypawar

2020-10-03 17:13 UTC, abhaypawar commented
Proofread and corrected major errors in translation thoroughly.
Please check @spielers @visshaljagtap.

Thanks again!

2020-10-04 12:00 UTC, spielers requested changes
Hey, @abhaypawar Thanks for your contributions. have suggested few more changes please resolve that.
so I can merge this.

2020-10-04 12:00 UTC, spielers commented on docs/docs/adding-forms.md
> +आता जेव्हा आपण क्लास कॉम्पोनन्ट तयार केला आहे तर आपण कॉम्पोनन्ट मध्ये `state` ऍड करू  शकतो.
remove the white spaces from karu shakta

2020-10-04 12:00 UTC, spielers commented on docs/docs/adding-forms.md
> +हा फॉर्म वापरकर्त्याची माहिती दाखवण्याव्यतिरिक्त काही अतिरिक्त करत नाही. या वेळी, आपण हा फॉर्म एका कॉम्पोनन्ट कडे हलवू शकता, फॉर्म स्टेट बॅकएंड सर्वरवर पाठवा, किंवा रोबस्त मान्यता जोडा. तुम्ही अप्रति
मान्यता ==> validation it should be in English

2020-10-04 12:22 UTC, abhaypawar commented on docs/docs/adding-forms.md
> +आता जेव्हा आपण क्लास कॉम्पोनन्ट तयार केला आहे तर आपण कॉम्पोनन्ट मध्ये `state` ऍड करू  शकतो.
Done!

2020-10-04 12:23 UTC, abhaypawar commented on docs/docs/adding-forms.md
> +हा फॉर्म वापरकर्त्याची माहिती दाखवण्याव्यतिरिक्त काही अतिरिक्त करत नाही. या वेळी, आपण हा फॉर्म एका कॉम्पोनन्ट कडे हलवू शकता, फॉर्म स्टेट बॅकएंड सर्वरवर पाठवा, किंवा रोबस्त मान्यता जोडा. तुम्ही अप्रति
Corrected. Please check.
Thanks @spielers and please review - @visshaljagtap

2020-10-04 13:04 UTC, spielers approved these changes

2020-10-04 13:05 UTC, merged