Update index.md
gatsbyjs/gatsby-mr pull request #31
Opened 2020-10-17 13:19 UTC by spathak98

@spielers I have updated the file, Please look in to it.

2020-10-17 13:29 UTC, spielers commented
@spathak98 have you aiming for Hacktoberfest ?? Do let us now will add the label to it.

Best
spielers

2020-10-23 15:33 UTC, spathak98 commented
hey @spielers  I am aiming for Hacktoberfest, so please add Hacktoberfest label.

2020-10-23 15:44 UTC, spielers requested changes
Hey, @spathak98 please do the required changes

Best,
spielers

2020-10-23 15:44 UTC, spielers commented on docs/tutorial/part-two/index.md
> +## जागतिक शैली वापरणे
शैली वापरणे = >ग्लोबल स्टईल्स

2020-10-23 15:44 UTC, spielers commented on docs/tutorial/part-two/index.md
> +प्रत्येक साइटवर काही प्रमाणात जागतिक शैली असते. यात साइटचे टायपोग्राफी आणि पार्श्वभूमी रंग यासारख्या गोष्टी समाविष्ट आहेत. या शैलींनी साइटची संपूर्ण भावना निश्चित केली आहे - भिंतीचा रंग आणि पोत जसे ख
ग्लोबल स्टईल्स use this

2020-10-23 15:44 UTC, spielers commented on docs/tutorial/part-two/index.md
> +### मानक सीएसएस फायलीसह जागतिक शैली तयार करीत आहे
ग्लोबल स्टईल्स

2020-10-23 15:44 UTC, spielers commented on docs/tutorial/part-two/index.md
> +नवीन तयार करून प्रारंभ करा Gatsby site. हे सर्वोत्तम असू शकते (विशेषत: जर आपण कमांड लाइनमध्ये नवीन असाल) आपण वापरलेल्या टर्मिनल विंडो बंद करण्यासाठी [part one](/tutorial/part-one/) आणि भाग दोन साठी न
नवीन तयार करून प्रारंभ करा Gatsby site.  === > please retanslate this

2020-10-23 15:44 UTC, spielers commented on docs/tutorial/part-two/index.md
> +एक नवीन टर्मिनल विंडो उघडा, `tutorial-part-two` नावाच्या निर्देशिकेत एक नवीन "hello world" Gatsby site तयार करा आणि नंतर या नवीन निर्देशिकेत जा:
directory  == > डिरेक्टरी  it should be the same as it is.

2020-10-23 15:44 UTC, spielers commented on docs/tutorial/part-two/index.md
> +#### ✋ CSS फाइलमध्ये शैली जोडा
शैली ==> स्टईल्स

2020-10-23 15:44 UTC, spielers commented on docs/tutorial/part-two/index.md
> +> टीप: आपण इच्छित असल्यास आपल्या कोड संपादकाचा वापर करून या निर्देशिका आणि फायली तयार करा.
निर्देशिका ==> should be a directory

2020-10-23 15:44 UTC, spielers commented on docs/tutorial/part-two/index.md
> +CSS-in-JS हा घटक-आधारित स्टाईल दृष्टीकोन आहे. सामान्यत :, हा एक नमुना आहे जेथे जावास्क्रिप्ट वापरुन [CSS is composed inline using JavaScript](https://reactjs.org/docs/faq-styling.html#what-is-css-in-
जावास्क्रिप्ट == > it should be in english

2020-10-26 03:02 UTC, visshaljagtap requested changes

2020-10-26 03:02 UTC, visshaljagtap commented on docs/tutorial/part-two/index.md
> +#### ✋ CSS मॉड्यूल्स वापरुन एक नवीन पृष्ठ तयार करा
dont translate page, keep as is

2020-10-30 06:38 UTC, spathak98 commented
Hey @spielers I have changed the required changes, please look into it.

2020-10-30 15:46 UTC, spielers commented
Hey, @visshaljagtap accepted for merging?

2020-11-11 04:57 UTC, visshaljagtap commented
Yes @spielers 
Thanks for the contribution @spathak98 

LGTM!

2020-11-11 04:57 UTC, visshaljagtap approved these changes

2020-11-17 12:25 UTC, spielers approved these changes
Cheers 😊!

2020-11-17 12:25 UTC, merged