translated docs/recipes/styling-css
gatsbyjs/gatsby-mr pull request #36
Opened 2020-10-25 17:43 UTC by k-guy-dev

completed the translation of doc/recipes/styling-css

2020-10-25 17:53 UTC, spielers requested changes
Hey @k-guy-dev  please retranslate the entire document once again with Marathi sentence Grammer keeping in mind.

And also Let us know if you are aiming for hacktoberfest.

Best,
spielers

2020-10-25 17:53 UTC, spielers commented on docs/docs/recipes/styling-css.md
> +## वापरत आहे global CSS फायली विना Layout component
global CSS फायल विना वापरण्यासाठी

2020-10-25 17:53 UTC, spielers commented on docs/docs/recipes/styling-css.md
> +- विद्यमान [Gatsby site](/docs/quick-start/) सह index page component
retranslate this, please.

2020-10-25 17:53 UTC, spielers commented on docs/docs/recipes/styling-css.md
> +1. तयार करा एक global CSS फाईल म्हणून `src/styles/global.css` आणि खालील फाईलमध्ये पेस्ट करा:
global CSS फाईल म्हणून `src/styles/global.css` तयार करा आणि खालील फाईलमध्ये पेस्ट करा :

2020-10-25 18:31 UTC, k-guy-dev commented
> Hey @k-guy-dev please retranslate the entire document once again with Marathi sentence Grammer keeping in mind.
> 
> And also Let us know if you are aiming for hacktoberfest.
> 
> Best,
> spielers

yup @spielers ,, I'm aiming for hacktoberfest

2020-10-26 02:58 UTC, visshaljagtap requested changes

2020-10-26 02:58 UTC, visshaljagtap commented on docs/docs/recipes/styling-css.md
> +## global CSS फायल विना वापरण्यासाठी
लेआउट कौम्पोनॅन्ट विना global CSS फाईल्स वापरणे

2020-10-26 02:58 UTC, visshaljagtap commented on docs/docs/recipes/styling-css.md
> +- [Gatsby site](/docs/quick-start/) index page component
[Gatsby site](/docs/quick-start/) index page component -> विद्यमान [Gatsby site](/docs/quick-start/) अनुक्रमणिका page कौम्पोनॅन्ट

2021-06-27 15:57 UTC, spielers commented
Hey @k-guy-dev Thanks for your contributions but I would suggest you should translate something from the `tutorials/` section

2021-10-03 14:53 UTC, spielers approved these changes
Thanks @k-guy-dev

2021-10-14 08:41 UTC, spielers commented
Thanks, @k-guy-dev  💐

2021-10-14 08:41 UTC, merged