Translated this page in Marathi
gatsbyjs/gatsby-mr pull request #44
Opened 2021-06-27 16:58 UTC by Abdulhussainjarif

2021-06-27 17:13 UTC, spielers requested changes
Hey @Abdulhussainjarif  Thanks for your efforts 💐
Suggested some changes please fix this will get you merged 😀

Best,
spielers

2021-06-27 17:13 UTC, spielers commented on docs/tutorial/part-six/index.md
> +> हे ट्यूटोरियल गॅट्सबीच्या डेटा लेयर बद्दलच्या मालिकेचा एक भाग आहे. आपण जात असल्याचे सुनिश्चित करा [भाग 4](/tutorial/part-four/) आणि [भाग 5](/tutorial/part-five/) येथे सुरू ठेवण्यापूर्वी.
आपण जात असल्याचे सुनिश्चित करा -> आपन हे एर्टिकल काळजीपुरवाक वाचल ही आपेक्षा

2021-06-27 17:13 UTC, spielers commented on docs/tutorial/part-six/index.md
> +मागील ट्युटोरियलमध्ये स्त्रोत प्लगइन डेटा कसा आणतात हे दर्शविले _into_ गॅटस्बीची डेटा सिस्टम या ट्यूटोरियल मध्ये, आपण ट्रान्सफॉर्मर प्लगइन कसे शिकू शकाल _transform_ स्त्रोत प्लगइनने आणलेली कच्ची सामग
कसे add after this -> कसे वापरु

2021-06-27 17:13 UTC, spielers commented on docs/tutorial/part-six/index.md
> +_about_ फायली परंतु आपण डेटा क्वेरी करू इच्छित असल्यास काय _inside_ फायली?
need to retranslate this

2021-06-27 17:13 UTC, spielers commented on docs/tutorial/part-six/index.md
> +हे शक्य करण्यासाठी, Gatsby ट्रान्सफॉर्मर प्लगइनचे समर्थन करते जे कच्चे करतात
जे कच्चे -> जे कच्चा डेटा आयत कर्ते

2021-06-27 17:13 UTC, spielers commented on docs/tutorial/part-six/index.md
> +परंतु आपला एक ब्लॉग पोस्ट थोडा एकटा दिसत आहे. तर दुसरा एक इन जोडा
इन -> remove this

2021-06-27 17:13 UTC, spielers commented on docs/tutorial/part-six/index.md
> +जे छान दिसते! वगळता… पोस्ट ऑर्डर चुकीचे आहे.
वगळता…  -> तारिही

2021-06-27 17:36 UTC, Abdulhussainjarif commented
@spielers I have made all the suggested changes, please let me know if you need more changes!

Regards, 
Abdulhussain Jarif

2021-07-09 07:20 UTC, spielers approved these changes
Hey, @Abdulhussainjarif  Thanks

Best,
spielers,

2021-07-09 07:21 UTC, merged