Translated docs/node-api-helpers file
gatsbyjs/gatsby-mr pull request #48
Opened 2021-07-09 09:32 UTC by Abdulhussainjarif

2021-10-02 15:05 UTC, spielers approved these changes
Thanks, @Abdulhussainjarif !!!
Will get you merged.

2021-10-02 15:06 UTC, spielerstudio approved these changes

2021-10-03 03:18 UTC, visshaljagtap requested changes

2021-10-03 03:18 UTC, visshaljagtap commented on docs/docs/node-api-helpers.md
> +सामान्य convention is to destructure helpers right in argument यादी:
Please properly translate this

2021-10-03 03:18 UTC, visshaljagtap commented on docs/docs/node-api-helpers.md
> +पहिला Argument प्रत्येकाला पास झाला. [Gatsby’s Node APIs](/docs/node-apis/) एक वस्तू आहे containing एक जोड of helpers . Helpers shared by all Gatsby’s Node APIs are दस्तऐवज in [Shared helpers](#share
Please properly translate this

2021-10-13 20:38 UTC, merged